export interface WordsByDifficulty {
  easy: string[];
  medium: string[];
  hard: string[];
}

export const words: WordsByDifficulty = {
  easy: [
    'Cry',
    'Mob',
    'Tip',
    'Fate',
    'Nap',
    'Sham',
    'Thud',
    'Fake',
    'Heel',
    'Jolt',
    'Seed',
    'Anew',
    'Fiji',
    'Guam',
    'Iwan',
    'Muse',
    'Sink',
    'Whim',
    'Golf',
    'Cell',
    'Doze',
    'Love',
    'Oops',
    'Stare',
    'Whip',
    'A shot',
    'Cheat',
    'Fault',
    'SWALK',
    'Corn',
    'Bogus',
    'Elite',
    'Heidi',
    'Manta',
    'Raves',
    'Slang',
    'Thumb',
    'Alice',
    'Child',
    'Eerie',
    'Grief',
    'Macho',
    'Pants',
    'See ya',
    'Stoop',
    'Truck',
    'Binge',
    'Hurrah',
    'Noble',
    'Tissue',
    'Ambush',
    'Chirp',
    'Halloo',
    'Sesame',
    'Stigma',
    'Apple',
    'Bug me',
    'Damage',
    'Iguana',
    'Mohawk',
    'Potato',
    'Ta ta',
    'Ace!',
    'Boo!',
    'Collar',
    'Fellow',
    'Greens',
    'Jet lag',
    'Riddle',
    'Sowing',
    'Unfair',
    'Wow!',
    'Boaster',
    'Devour',
    'Excuse',
    'Garcon',
    'Jalopy',
    'Random',
    'Shut up',
    'Sweater',
    'You bet',
    'Cabaret',
    'Fasting',
    'Measles',
    'Pay day',
    'Shawnee',
    'TV stars',
    'Codfish',
    'Giraffe',
    'Outland',
    'Sunrise',
    'Trivial',
    'Pegasus',
    'Bad debt',
    'Brewery',
    'Harmony',
    'No sweat',
    'Stay put',
    'Aahh!',
    'Bear rug',
    'Braggart',
    'Cut here',
    'Excited',
    'Gen X',
    'Grumble',
    'Invalid',
    'No no',
    'Perilla',
    'Sea lion',
    'Tax free',
    'Vietnam',
    'Anemone',
    'Crosstie',
    'Fish dish',
    'Gross!',
    'Marathon',
    'Resolute',
    'Ticklish',
    'A for ABC',
    'Calamari',
    'Drainage',
    'Familiar',
    'Hangnail',
    'Mail box',
    'Outstrip',
    'Retainer',
    'Splat!',
    'Ticktack',
    'Ali Baba',
    'Brace up',
    'Contrary',
    'Fugitive',
    'Negative',
    'Pressure',
    'Suddenly',
    'Wee hours',
    'Chill out',
    'Demotion',
    'Elaborate',
    'Ignition',
    'Mackerel',
    'Nuisance',
    'Raccoons',
    'Slower',
    'Toe to toe',
    'Whiz kids',
    'Amaryllis',
    'Birthmark',
    'Cover up',
    'Globefish',
    'Hydrangea',
    'Jellyfish',
    'Low rider',
    'Pumpkin',
    'Sour milk',
    'Unsettled',
    'Babylonia',
    'Crash cart',
    'Embezzle',
    'Good twist',
    'Lanky man',
    'Sideburns',
    'Time trip',
    'Water flea',
    'Daredevil',
    'Dumb luck',
    'Hair weave',
    'High hopes',
    'Lollipop',
    'Pink tofu',
    'Sweet life',
    'Turtle leg',
    'Alpha wave',
    'Chopin',
    'Egg head',
    'Fledgling',
    'Left field',
    'Oolong tea',
    'Rock trout',
    'Small face',
    'Spooky!',
    'Vacancies',
    'Begone!',
    'Chatterbox',
    'Errand boy',
    'Instant hit',
    'Middle age',
    'Oversleep',
    'Suits tribe',
    'Aussie beef',
    'Broken off',
    'Cornstarch',
    'Eccentric',
    'Freeloader',
    'Hair piece',
    'In a pinch',
    'Laugh track',
    'Out of time',
    'Stereotype',
    'Vamoosh!',
    'Call us now',
    'Flash a card',
    'Miami rice',
    'Now what?',
    'Red tractor',
    'Shady grove',
    'Temptation',
    '.com kids',
    'Average Joe',
    'Eurotunnel',
    'Get them all',
    'Now I get it',
    'Power play',
    'Smart guy',
    'Tie in a row',
    'Act your age',
    'Busy as a bee',
    'Crying fits',
    'Field of hay',
    'Nozzle',
    'Rage of fans',
    'This for par',
    'Two faced',
    'At full blast',
    'Blue Monday',
    'Donkey ride',
    'Frilly tutus',
    'Grudge love',
    'Joys of life',
    'Lovely chef',
    'Out of focus',
    'Under wraps',
    'Young blood',
    'Broken heart',
    'Ear guitar',
    'Hasta la vista',
    'Iron maiden',
    'Mesh of a net',
    'National PC',
    'Parting shot',
    'Sink or swim',
    'Step outside',
    'Washboard abs',
    'Wooden gong',
    'Carelessness',
    'Dried up air',
    'Gastrocamera',
    'Highly toxic',
    'Inline skate',
    'Lydian scale',
    'Pickpocket',
    'Regular size',
    'Soul for sale',
    'Time is ripe',
    'Walking debt',
    'Call the tune',
    'Family traits',
    'Hopeless',
    'Marbled beef',
    'Pass the buck',
    'Satellite DNA',
    'Why ask me?',
    'Alaska fair',
    'Connecticut',
    'Feel my pain',
    'Heavy makeup',
    'Jellied soup',
    'Ok, you win',
    'Rust proof',
    'Sneezing fit',
    'Trainee monk',
    'Wooing pause',
    'Anguished ace',
    'Debut recital',
    'Fancy one?',
    'Genetic line',
    "I'll be back",
    'Members only',
    'Pommel horse',
    'Sesame flavor',
    'Steal your way',
    'Touchdown!',
    'Yarble barble',
    'Constriction',
    'Dessert spoon',
    'Enormous hair',
    'IQ1300',
    'Love is blind',
    'Overachiever',
    'Prepaid card',
    'Sprinkle salt',
    'Trick or treat',
    'You have whale',
    'Allergy tested',
    'But not for me',
    'Cricked neck',
    'Find yourself',
    'Generic pasta',
    'Hero of the day',
    'Japanese beef',
    'Nasal uniform',
    'Poughkeepsie',
    'The McCulture',
    'Yum, yum!',
    'Blue with cold',
    'Deadly poison',
    'Film subtitles',
    'Gel and mousse',
    'Hitchhike a bus',
    'Is it a bird?',
    'Mark me absent',
    'Pet detective',
    'Rice crackers',
    'Sit up straight',
    'Topsy turvy',
    'A handy tote hag',
    'Claws and fists',
    'Evolved sharks',
    'Game preserve',
    'Honk your nose',
    'Loads of money',
    'Rice ball face',
    'Toil and grind',
    'Win by an inch',
    'Ask the machine',
    'Double or quit',
    'Get a taste of it',
    'Herbal vinegar',
    'Know your nose',
    'Monkey wrench',
    "No man's land",
    'Platonic love',
    'Teething fever',
    "Can't hear you",
    'Elevator music',
    'Friendly giant',
    'Highway of love',
    'Just be patient',
    'Mad cow disease',
    'My goodness!',
    'Sacrifice bunt',
    'Stand at ease!',
    'An array of lies',
    'Brain capacity',
    'Deep sea fish',
    'Fund raising',
    'In the wee hours',
    'Pie in the face',
    'Soapbox nation',
    'The seventh seal',
    'Up to my elbows',
    "You're doomed",
    'Black tie event',
    'Computer geeks',
    'Dragnet fishing',
    'Giveaway price',
    "I'll show mine",
    "Life's a gas!",
    'Right off the bat',
    "Two's company",
    'Wind direction',
    'Black as thunder',
    'Crocodile tears',
    'Food poisoning',
    'Grin and bear it',
    'In my next life',
    'Lose gracefully',
    'Must be an error',
    'Ophthalmologist',
    'Rabble rouser',
    'Smooth as velvet',
    "There's a crowd",
    'Banned language',
    'Carrot and stick',
    'Deviation value',
    'Fake up artist',
    'Gamma GTP level',
    'High school ring',
    "I'll have a half",
    'Passive attitude',
    'Yadda yadda yadda',
    'Crane and turtle',
    "Don't we all?",
    'Flamenco lesson',
  ],
  medium: [
    'Go night night',
    'Jungle jamboree',
    'Milk on whiskers',
    'Pick your brain',
    'Swimming trunks',
    'Toothless dentist',
    "You'll be sorry",
    'Barrel chested',
    'Dutch apple pie',
    'Garbage foraging',
    'Hypnotic trance',
    'Lingering scent',
    'Nabbed in the act',
    'Picnic feeling',
    'Roll your tongue',
    'Smash you to atoms',
    'To be or not to be',
    'Www.sega.com',
    'Back to the studio',
    'Complete weirdo',
    'Dress for success',
    'Freeze, please',
    'Have mercy on me',
    'In all of a dither',
    'Radical argument',
    'Spartan aesthetic',
    'Thorn in my flesh',
    'Used car salesman',
    'With sponsorship',
    'After a lot of fuss',
    'Finger pointing',
    'I C U C No C Tru C',
    "Let's make it bad",
    'My brain is fried',
    'Pathetic no mind',
    'Somebody help me',
    'Vroom with a view',
    'A stack of excuses',
    'Burned to a crisp',
    'I have a sore trout',
    'Jarring situation',
    'Loch Ness monster',
    'Naughty nightmare',
    'Paper pushing',
    'Potato with butter',
    'Reluctant to lend',
    'Slayer of evil!',
    'This looks no good',
    'Armed with bananas',
    'Blood transfusion',
    'Colossus of Rhodes',
    'Eyelashed together',
    'Grudge over foods',
    'More beans please',
    'No pan in ten did',
    'Say it with flowers',
    'The door is that way',
    'A tinge of anxiety',
    'Belgian chocolate',
    'Disappearing ink',
    'Eyeball to eyeball',
    'Go out in glad rags',
    'Hug trees not bears',
    'Life is but a dream',
    'My mother country',
    'Yeee hawwwww!',
    'Antique computer',
    'Bookmark this page',
    'Cozy as a warehouse',
    'Do not pass through',
    'Free trade status',
    'Homecoming dance',
    'Make up your mind',
    'Old popular songs',
    'Risk of being seen',
    'Strikes and gutters',
    'They gave up on me',
    'Whitecollar crime',
    'Caribbean Iced Tea',
    'Double crossing',
    'Green caterpillar',
    'Looking for my cat',
    'Moisture in the air',
    'Nobody eat anybody',
    'Sugar and cream?',
    'Waiters in a trance',
    'Your bus is on fire',
    'Alphabetical order',
    'Farewell to my past',
    'Hitting .230',
    'Logic of the strong',
    'Psychedelic macho',
    'Sounds like fun!',
    'Waxed up surfboard',
    'Abominable shocker',
    "Can't ask for more",
    'Green eyed monster',
    'Lie, cheat, fake',
    'Nauseating flattery',
    'Pseudo Polynesian',
    'Social abomination',
    'Sweet and sour pork',
    'Digestible termites',
    'Hit by the recession',
    'Lie your way through',
    'More in the kitchen',
    'Off the beaten track',
    'Spinning elephant',
    'This is how it started',
    "Who's sorry now?",
    'Abominable snowman',
    'Bye bye, Columbus',
    "Finger pullin'",
    "I've got a waterbed",
    'Limited engagement',
    'Miss out by a mistake',
    'Spaghetti Bolognese',
    'The Statue of Liberty',
    'A shortage of dwarves',
    'Bar codes on roaches',
    'Compusing to me?',
    'Employment ice age',
    'Guppy love is great',
    'Miserably beaten up',
    'Nobody gets younger',
    'The Smashing Windows',
    'Why him, not me?',
    'Arrested all too soon',
    'Cheesy one liners',
    'Gifted green finger',
    "I am fortune's fool",
    "I'm so fantastic!",
    'Kept in after school',
    'Really disingenuous',
    'Walk on the wild side',
    'A sweeping statement',
    'Clean credit history',
    'Indomitable resolve',
    'Love me to my marrow',
    'Possessive grasping',
    'Shame about your face',
    'The truth of the rumor',
    "We're not as we were",
    "Ain't gonna miss!",
    'Cheers, big ears!',
    "Don't patronize me",
    'Friend kindergarten',
    'Huffing and puffing',
    "I've grown isolated",
    'Make yourself at home',
    'Real job with a future',
    'Typing the night away',
    'You can do without me',
    'A two year contract',
    'Come on, my son!',
    'Ethically challenged',
    'Goldfish chewing gum',
    'Long legged uncle',
    'Open eyed slumber',
    "Shark's fin again?",
    'Storm of liquidation',
    "What's up, dude?",
    'Beautiful friendship',
    "Don't you cry, boy",
    'Front page scandal',
    'Hello and welcome!',
    'Intellectual offense',
    'Ludwig van Beethoven',
    'Plain, simple fact',
    'Totally unacceptable',
    'You gave me the power',
    'Casanova and Don Juan',
    'Fading consciousness',
    'Humanity documentary',
    'Impeachment process',
    'Public relations man',
    'Smiling like an idiot',
    'Weekend trip to Kyoto',
    "You're on curfew!",
    'Chip away to the stones',
    "Don't blame yourself",
    'Find anyone with a car',
    'Headbanging gray heads',
    'Unexpected accident',
    'A sense of proportion',
    'Chain saw sculpture',
    'Fugitive from justice',
    'Left me in a minor key',
    'National Noodle Party',
    "Rock'n'roll is dead",
    'Translucent computer',
    'Aptitude for painting',
    'Give me my money back',
    'Indecisive commitees',
    'Nippon cha cha cha!',
    'Walking advertisement',
    "You can't sell that!",
    'A hop, skip and jump',
    'Generic no name brand',
    'Made for TV movie',
    'Prehistoric basketball',
  ],
  hard: [
    'Currency restrictions',
    'Feed pigeons in a park',
    'If in doubt, think!',
    'May luck be with you!',
    'Nobody buys me nothing',
    "Rock'em til they drop",
    "Can't live without you",
    "Don't come any closer",
    'Have you seen my dog?',
    'Jelly and Tuna sandwich',
    'Protein goes bad easily',
    'The ultimate has beens',
    '7 wonders of the world',
    'Do amoebas feel love?',
    "He's still watching you",
    "It's definitely a cheat",
    'Perfect holiday weather',
    'They had an a greed meant',
    'A goldfish named Dorothy',
    'Be happy somewhere else',
    'Curiosity killed the cat',
    'It was just a game for you',
    'One year of unpaid rent',
    'Screamer roller coaster',
    'Up to the expense limit',
    "You've got a curfew?",
    'Come here, let me feel',
    "Haven't got my name yet",
    "I wouldn't forgive you",
    'We welcome any requests',
    'You are useless to me now',
    'Charisma without license',
    'Evade the ticket machine',
    "I'm voting with my feet",
    'Neglect everything else',
    'Sure plays mean pinball',
    'Who used my toothbrush?',
    'Beyond my wildest dreams',
    'In greater or less degree',
    'Lip sync to the lyrics',
    'Play catch up with you',
    'Useful rock paperweight',
    '5 minutes into the game',
    'Devote life to beef bowls',
    "Garage sales man's pitch",
    'See you later, alligator',
    'Welcome to the real world',
    "Your tears can't fool me",
    'Carry baby in a paper bag',
    'Marshmallow grizzly bear',
    'Beware the brides of March',
    "Don't try to be my mother",
    'Gyroscopic proportions',
    'I really admire your shoes',
    'Mobile phone revolution',
    "You're breaking my heart",
    'Pencil lead is poisonous',
    'Treasury of terrible jokes',
    '4 days with nothing to eat',
    'Day to day management',
    'Living in a cardboard box',
    'Say it with plastic flowers',
    "What's to become of me?",
    'Climb the statue of liberty',
    'Eat everything on the menu',
    'Jolly good show, chap!',
    "Nice kilt you're wearing",
    'Small basket in a big basket',
    'Dance in the disco go go go',
    'Fragile, handle with care',
    'Look, here he comes again',
    'Some who go sip also gossip',
    'We must be over the rainbow',
    "Can't get no disinfectant",
    'Intervertebral disk hernia',
    'On tour around Saskatchewan',
    'The worst scandal in history',
    "You can't get away from me",
    'Condemned child criminal',
    "I don't need your comfort",
    'Long way to the major league',
    'Rich, bored and beautiful',
    "If you want it, it's yours",
    'Too hard for a dummy like me',
    'Did the devil show up yet?',
    'Have you seen a chicken fish',
    "Let's not wait and do it now",
    'The prince of pickpockets',
    'What time do you call this?',
    'Christmas sales competition',
    'How long is "a while"?',
    "Let's put our city on a map",
    'Sound of one hand clapping',
    'Wrong command or file name',
    'Hard to tell right from wrong',
    'Money, money, money!',
    'Dispensable public offices',
    "He's a bull, I'm a matador",
    'The joke turned out to be true',
    "You'll laugh, you'll cry",
    'Keep pressing the fire alarm',
    'Turn back while you still can',
    'Are my suspenders straight?',
    'Embarrassing and humiliating',
    "I won't let you have your way",
    'Put your hand in your pocket',
    'Wheered you git that turkey?',
    'Bandanna originated in India',
    "Prince in sheep's clothing",
    'You dirty rotten swine you!',
    'Fanning the flames of passion',
    'Let me introduce myself first',
    'What is the meaning of void?',
    'Look both ways before crossing',
    "We'll be on the evening news",
    'Hand says much about the person',
    'Private e mails are scanned',
    "The world's longest sushi roll",
    'Booing as big as earth rumbling',
    'Color the X rays with crayons',
    'What do you think, officer?',
    'Can I use your parking spot?',
    "How come he doesn't notice?",
    'Miles and miles of open fields',
    'Who taught you to walk that way?',
    'Gain advantage by complaining',
    'Stop worrying about everything',
    'Black cat with a fish in its mouth',
    'How would you like your steak?',
    'Karaoke king is what they call me',
    'Stolen painting found by a tree',
    'Carried shoulder high to the door',
    "Let's continue the affirmation",
    'Would you like fries with that?',
    "I know it, just can't spell it",
    "Put it on the company's credit",
    'He shoots... he scores!!',
    'Vehicle towed at owners expense',
    'Good reputation among neighbors',
    'My pride has been torn to pieces',
    'This is your captain speaking!',
    "Can't you spare a dime or two?",
    "If you can't be kind, be vague",
    'Please stop the voices in my head',
    'Waistline threatening expansion',
    'I only do autographs after the show',
    "We won't be able to go home alive",
    'Devilishly devious Danish dentist',
    'I wonder if Dracula ever has ticks',
    'Wanna leave a memory not a record',
    'Click here to hidden web addresses',
    'Little pet food for little animals',
    'Transformation from a duet to duel',
    'Comprehensive physical checkup',
    'Take this! And this! And this!',
    'Engage brain before starting mouth',
    'My personality is my strong point',
    "I'd kill for a Nobel Peace Prize",
    'Secret squirrel & Morocco mole',
    "Are you aware you're in trouble?",
    "I don't want to see that sullen face",
    'Please keep your seatbelts fastened',
    "You don't know what you're saying",
    'It was back when you meant something',
    'I did my best is not an excuse',
    'A bird in hand is worth two in the bush',
    'It takes 5 years to heal completely',
    'Unearned success to wretched excess',
    'Ugliness and beauty of everyday life',
    'Got 2 chocolate bars for my birthday',
    'What made you come all the way here?',
    "Are you feeling what I'm feeling?",
    'Librarian from Marshfield Wisconsin',
    'The last Sunday in the summer vacation',
    'Call our agency in your neighborhood',
    'Impossibly good natured landowner',
    'Your fingerprints were on the window',
    'That cheesecake looks too good to resist',
    'Conversation between a cow and a horse',
    'Think about a good excuse to play hooky',
    'This music sounds like a military march',
    'Are you playing this with one finger?',
    'Going at warp speed is bad for your age',
    'The plan went wrong from the beginning',
    'Eat extra large fries without any guilt',
    'Ten copies of a $10 bill, please',
    'Paperback writer, take a bath right now',
    'Please refrain from smoking at all times',
    'Free drink opportunities along the way',
    'When in doubt, consult your inner child',
    'Not by the hair of my chinny chin chin',
    'Looking for a D D free, intelligent man',
    'Zanily zit zapping Zimbabwean zoologist',
  ],
};
